FROM node:23-alpine

WORKDIR /app 


RUN --mount=type=cache,target=/root/.npm \
	npm install -g pnpm@${PNPM_VERSION}


COPY package.json  pnpm-lock.yaml pnpm-workspace.yaml ./

RUN pnpm install 

COPY . . 

EXPOSE 5173

CMD ["pnpm", "dev",  "--host"]