FROM python:3.13-slim

# Install uv.
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /app 

# install project dependencies using lockfile & settings 
# this lets us cache this stuff so it doesnt have to be reinstalled on any change to app code
RUN --mount=type=cache,target=/root/.cache/uv \
	--mount=type=bind,source=uv.lock,target=uv.lock \
    --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
    uv sync --locked --no-install-project

# then, add the rest of the project and install it
COPY . /app 
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --locked

# Place executables in the environment at the front of the path
ENV PATH="/app/.venv/bin:$PATH"	

CMD ["fastapi", "dev", "app/main.py", "--port", "3000", "--host", "0.0.0.0"]

# uv run fastapi dev ./app/main.py --port 3000